"""In-memory index of the Odin knowledge base (Phase 3).

This module parses `odin-knowledge-base/INDEX.md` (the file generated by `_Helpers/scripts/indexing/build_kb_index.py`) and exposes lookups that the `code_auditor` reporter uses to attach KB context under each finding.

The index is intentionally narrow:

- It is **read-only** - never modifies the file on disk.
- It is **lazy** - the file is parsed on first access, then cached.
- It is **tolerant** - a missing or malformed INDEX degrades gracefully to an empty index (findings fall back to their `kb_sources` list without context).
- It is **stdlib-only** - no third-party dependency.

Public surface:

- `KBIndex` - the in-memory index. `__init__` does NOT parse; call any lookup method to trigger the parse, or call `ensure_loaded()` explicitly.
- `KBIndex.all_files() -> list[str]` - every KB file path referenced by the index, normalised with forward slashes, deduplicated, sorted.
- `KBIndex.lesson_to_file(lesson_id: str) -> str | None` - resolve a Skool or Karl book numeric lesson ID to its INDEX-linked file path (or `None`).
- `KBIndex.files_for_finding(finding) -> list[str]` - convenience helper that combines `finding.kb_sources` with topic-based fallbacks derived from `finding.category` and `finding.title`.

The module purposefully uses pathlib only (no `os.path`) and forwards slashes in every string output, per AGENTS.md § Python conventions.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

if TYPE_CHECKING:
    from scanner import Finding


_AUTO_BEGIN = "<!-- BEGIN AUTO"
_AUTO_END = "<!-- END AUTO"
_MANUAL_BEGIN = "<!-- BEGIN MANUAL"
_MANUAL_END = "<!-- END MANUAL"


_MD_LINK_RX = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_HEADING_RX = re.compile(r"^(#{1,6})\s+(.+?)\s*$", re.MULTILINE)
_BULLET_RX = re.compile(r"^\s*[-*]\s+(.*?)\s*$", re.MULTILINE)
_BACKTICK_PATH_RX = re.compile(r"`([^`]*\.(?:md|odin))`")
_TABLE_ROW_RX = re.compile(r"^\|.*\|\s*$", re.MULTILINE)


_DEFAULT_KB_ROOT = Path("odin-knowledge-base")
_DEFAULT_INDEX_REL = Path("odin-knowledge-base/INDEX.md")


def _normalise(path_str: str) -> str:
    """Return `path_str` with forward slashes only and no surrounding whitespace."""
    return path_str.strip().replace("\\", "/")


def _looks_like_kb_path(candidate: str) -> bool:
    """Heuristic: does this string look like a repo-relative KB file path?"""
    if not candidate:
        return False
    norm = _normalise(candidate)
    if norm.startswith(("http://", "https://", "mailto:")):
        return False
    if "\n" in norm or " " in norm:
        return False
    return norm.startswith(
        (
            "odin-knowledge-base/",
            "code/",
            "_Helpers/docs/",
        )
    ) and (norm.endswith(".md") or norm.endswith(".odin"))


def _extract_links(text: str) -> list[str]:
    """Pull every Markdown link target out of `text`. Forward-slash normalised."""
    out: list[str] = []
    for m in _MD_LINK_RX.finditer(text):
        target = _normalise(m.group(2))
        if _looks_like_kb_path(target):
            out.append(target)
    return out


def _extract_backtick_paths(text: str) -> list[str]:
    """Pull `` `path/to/file.md` `` references out of `text`."""
    out: list[str] = []
    for m in _BACKTICK_PATH_RX.finditer(text):
        target = _normalise(m.group(1))
        if _looks_like_kb_path(target):
            out.append(target)
    return out


def _extract_zone(text: str, begin_marker: str, end_marker: str) -> str:
    """Return the substring of `text` strictly between two HTML-comment markers.

    If a marker is missing, the matching zone boundary is the start/end of the file. The returned string is suitable for further parsing.
    """
    begin = text.find(begin_marker)
    if begin < 0:
        return ""
    begin = text.find("-->", begin)
    if begin < 0:
        return ""
    begin += len("-->")
    end = text.find(end_marker, begin)
    if end < 0:
        end = len(text)
    return text[begin:end]


@dataclass
class _TopicBucket:
    """A manual topic heading and the file paths it references."""

    heading: str
    files: list[str] = field(default_factory=list)


@dataclass
class _RawIndex:
    """Parsed contents of `INDEX.md`, ready to be queried."""

    all_files: list[str] = field(default_factory=list)
    lessons: dict[str, str] = field(default_factory=dict)
    topics: dict[str, _TopicBucket] = field(default_factory=dict)


def _parse_auto_zone(auto_text: str, raw: _RawIndex) -> None:
    """Parse the AUTO zone: tables + bullet lists + inline links.

    We rely on two cheap passes:

    1. Pull every Markdown link target out of the zone (catches tables and inline links uniformly).
    2. Pull every backtick-quoted path (catches bullet lists in the manual zone, but harmless here too).

    For lesson IDs, we look at the Karl book table where the `#` column is a plain integer and the second column holds the file path.
    We use a simpler heuristic: any link whose display text is exactly digits (1-4 chars) maps `display_text -> href`.
    This is the same shape the upstream `build_kb_index.py` generates for the Karl book table.
    """
    seen: set[str] = set()
    for m in _MD_LINK_RX.finditer(auto_text):
        target = _normalise(m.group(2))
        if not _looks_like_kb_path(target):
            continue
        if target not in seen:
            seen.add(target)
            raw.all_files.append(target)
        display = m.group(1).strip()
        if display.isdigit() and 1 <= len(display) <= 4:
            raw.lessons.setdefault(display, target)

    for path in _extract_backtick_paths(auto_text):
        if path not in seen:
            seen.add(path)
            raw.all_files.append(path)


def _parse_manual_zone(manual_text: str, raw: _RawIndex) -> None:
    """Parse the MANUAL zone: H3 topic headings followed by bullet lists.

    For every H3 heading `### Foo bar`, the bullets beneath it (until the next heading of equal or higher level) define a topic.
    Each bullet is matched for a backtick-quoted KB path; that path joins both the file index and the topic bucket.

    Headings are normalised to lowercase for case-insensitive lookup.
    """
    matches = list(_HEADING_RX.finditer(manual_text))
    if not matches:
        return
    topic_starts: list[tuple[int, str, int]] = []
    for i, m in enumerate(matches):
        level = len(m.group(1))
        heading_text = m.group(2).strip()
        body_start = m.end()
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(manual_text)
        if level == 3:
            topic_starts.append((level, heading_text, body_start))
            _ = body_end
    topic_ranges: list[tuple[str, int, int]] = []
    for i, (_level, heading, body_start) in enumerate(topic_starts):
        body_end = (
            topic_starts[i + 1][2] if i + 1 < len(topic_starts) else len(manual_text)
        )
        topic_ranges.append((heading, body_start, body_end))

    seen: set[str] = set()
    for path in _extract_links(manual_text):
        if path not in seen:
            seen.add(path)
            raw.all_files.append(path)
    for path in _extract_backtick_paths(manual_text):
        if path not in seen:
            seen.add(path)
            raw.all_files.append(path)

    for heading, body_start, body_end in topic_ranges:
        bucket = _TopicBucket(heading=heading)
        body = manual_text[body_start:body_end]
        for m in _BULLET_RX.finditer(body):
            line = m.group(1)
            for path in _extract_backtick_paths(line):
                bucket.files.append(path)
        seen_bucket = list(dict.fromkeys(bucket.files))
        bucket.files = seen_bucket
        key = heading.lower()
        if bucket.files:
            raw.topics[key] = bucket


class KBIndex:
    """In-memory, lazy-loaded KB index for the `code_auditor`.

    Construction does NOT parse - call any lookup method (or `ensure_loaded()`) to trigger parsing. Re-parsing is a no-op once `_loaded` is true.
    """

    def __init__(self, index_path: Path | None = None, kb_root: Path | None = None):
        self._index_path: Path | None = Path(index_path) if index_path else None
        self._kb_root: Path | None = Path(kb_root) if kb_root else None
        self._loaded = False
        self._raw = _RawIndex()

    @property
    def index_path(self) -> Path | None:
        """Return the resolved INDEX.md path (or `None` if not configured)."""
        return self._index_path

    @property
    def kb_root(self) -> Path | None:
        """Return the resolved KB root (or `None` if not configured)."""
        return self._kb_root

    def ensure_loaded(self) -> None:
        """Parse the INDEX file if not already loaded. Safe to call repeatedly."""
        if self._loaded:
            return
        self._loaded = True
        path = self._index_path
        if path is None or not path.is_file():
            return
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return
        auto_text = _extract_zone(text, _AUTO_BEGIN, _AUTO_END)
        manual_text = _extract_zone(text, _MANUAL_BEGIN, _MANUAL_END)
        _parse_auto_zone(auto_text, self._raw)
        _parse_manual_zone(manual_text, self._raw)
        deduped: list[str] = list(dict.fromkeys(self._raw.all_files))
        deduped.sort()
        self._raw.all_files = deduped
        self._raw.lessons = dict(sorted(self._raw.lessons.items()))

    def all_files(self) -> list[str]:
        """Return every KB file path the index knows about, sorted + deduped."""
        self.ensure_loaded()
        return list(self._raw.all_files)

    def lesson_to_file(self, lesson_id: str) -> str | None:
        """Resolve a Skool or Karl book numeric lesson ID to a file path.

        Accepts the ID as a string with or without a leading zero. Returns `None` if no mapping is known.
        """
        self.ensure_loaded()
        if not lesson_id:
            return None
        key = lesson_id.lstrip("0") or "0"
        return self._raw.lessons.get(key) or self._raw.lessons.get(lesson_id)

    def topic_to_files(self, topic_keyword: str) -> list[str]:
        """Return the files listed under any topic whose heading matches `topic_keyword`.

        Matching is case-insensitive substring against the heading text. The returned list is the deduped union of every matching bucket, sorted.
        """
        self.ensure_loaded()
        if not topic_keyword:
            return []
        needle = topic_keyword.lower()
        collected: list[str] = []
        for heading, bucket in self._raw.topics.items():
            if needle in heading:
                collected.extend(bucket.files)
        return list(dict.fromkeys(collected))

    def category_to_files(self, category: str) -> list[str]:
        """Map a `Finding.category` to a sensible topic keyword.

        This is the only place we hard-code the category -> topic mapping, so new categories can be added without touching the call sites.
        """
        mapping = {
            "allocator": ["memory", "alloc"],
            "data-structure": ["data-oriented", "language"],
            "anti-pattern": ["language"],
            "kb-compliance": ["workflow"],
            "architecture": ["workflow"],
            "style": ["language"],
        }
        out: list[str] = []
        for keyword in mapping.get(category, ["language"]):
            out.extend(self.topic_to_files(keyword))
        return list(dict.fromkeys(out))

    def files_for_finding(self, finding: "Finding") -> list[str]:
        """Pick a relevant, ordered list of KB files for one `Finding`.

        Ordering is: explicit `kb_sources` first (rule-declared), then any lesson refs resolved to known files, then topic matches derived from the rule's category and title.
        Duplicates are removed; the result is capped at 8 entries to keep the report readable.
        """
        self.ensure_loaded()
        seen: set[str] = set()
        ordered: list[str] = []
        for src in getattr(finding, "kb_sources", []) or []:
            norm = _normalise(str(src))
            if norm and norm not in seen:
                seen.add(norm)
                ordered.append(norm)
        for ref in getattr(finding, "lesson_refs", []) or []:
            target = self.lesson_to_file(str(ref))
            if target and target not in seen:
                seen.add(target)
                ordered.append(target)
        category = getattr(finding, "category", "")
        for path in self.category_to_files(category):
            if path not in seen:
                seen.add(path)
                ordered.append(path)
        title = getattr(finding, "title", "")
        if title:
            keyword = title.split()[0].lower() if title.split() else ""
            if keyword and len(keyword) >= 4:
                for path in self.topic_to_files(keyword):
                    if path not in seen:
                        seen.add(path)
                        ordered.append(path)
        return ordered[:8]


def build_default_index(repo_root: Path | None = None) -> KBIndex:
    """Build a `KBIndex` wired to the default INDEX.md location.

    Walks `repo_root / "odin-knowledge-base/INDEX.md"` if `repo_root` is given, otherwise uses a relative path that only resolves when the current working directory is the repo root (useful for tests).
    """
    if repo_root is None:
        return KBIndex(index_path=_DEFAULT_INDEX_REL, kb_root=_DEFAULT_KB_ROOT)
    return KBIndex(
        index_path=repo_root / "odin-knowledge-base" / "INDEX.md",
        kb_root=repo_root / "odin-knowledge-base",
    )


__all__ = ["KBIndex", "build_default_index"]
