"""_Helpers/book_html_to_md.py - Convert Karl's HTML book "Understanding the Odin
Programming Language" into ONE MD FILE PER CHAPTER + an index README.

The source HTML (3.6 MB) is split into:
- docs/karl_zylinski/odin-book/README.md                  (book index)
- docs/karl_zylinski/odin-book/01-introduction.md        (chapter 1)
- docs/karl_zylinski/odin-book/02-hellope-a-tiny-program.md
- ...
- docs/karl_zylinski/odin-book/appendices/A-handle-based-array.md
- ...

Each file <30-150 KB -> easy navigation, light Kilo context.

The HTML contains (structure observed v1.10):
- <head> with ~1 MB of base64 fonts (to remove)
- <style> screen/print/dark-mode CSS (to remove)
- <script> dark-mode + copy buttons (to remove)
- <div id="contents"> : duplicated TOC sidebar (to remove)
- <div id="cover">    : title page (to extract into metadata)
- <div class="chapter-heading"> : ONE per chapter (28)
    - <span class="chapter-heading-number">Chapter N</span>
    - <a id="..."><h1>Title</h1></a>
    - chapter content: sections, paragraphs, code

Usage:
python _Helpers/book_html_to_md.py [--src PATH] [--out-dir DIR] [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup, Tag
from bs4.element import NavigableString

from markdownify import markdownify as md

from _Helpers.lib.user_config import env_or_config

_DESCRIPTION = (
    "Convert Karl's HTML book into one MD file per chapter + a book index README."
)


# Source HTML of Karl's book. Read in this order:
#   1. CLI argument --src
#   2. environment variable BOOK_HTML_SRC
#   3. _Helpers/.private/user_config.json (field paths.karl_book_html)
#   4. empty string (the script will exit with a clear message)
DEFAULT_SRC = Path(env_or_config("paths.karl_book_html", "BOOK_HTML_SRC"))
DEFAULT_OUT = Path(
    env_or_config("paths.karl_book_out", "BOOK_HTML_OUT")
    or (Path(__file__).resolve().parent.parent / "docs" / "karl_zylinski" / "odin-book")
)

_STRIP_TAGS = {"style", "script", "noscript", "iframe", "svg", "form", "button"}
_STRIP_IDS = {
    "contents", "contents-main", "contents-show-button",
    "contents-heading", "cover", "dark-mode-button",
}


# ─── CLEANUP ───────────────────────────────────────────────────────────────
def _strip_chrome(soup: BeautifulSoup) -> None:
    for tag in soup.find_all(_STRIP_TAGS):
        tag.decompose()
    for el_id in _STRIP_IDS:
        for el in soup.find_all(id=el_id):
            el.decompose()
    for head in soup.find_all("head"):
        head.decompose()


def _clean_attrs(soup: BeautifulSoup) -> None:
    """Strip residual onclick/onload/style."""
    for el in soup.find_all(True):
        for attr in list(el.attrs):
            if attr.startswith("on") or attr == "style":  # type: ignore[attr-defined]
                del el.attrs[attr]


def _normalize_pre_blocks(soup: BeautifulSoup) -> None:
    """Mark every <pre> as Odin (the book is 100% Odin)."""
    for pre in soup.find_all("pre"):
        classes = pre.get("class") or []
        if isinstance(classes, str):
            classes = classes.split()
        if "language-odin" not in classes:
            classes.append("language-odin")
            pre["class"] = classes  # type: ignore[assignment]


# ─── GITHUB HEADING SLUG ─────────────────────────────────────────────────────
def _github_slugify(text: str) -> str:
    """Compute the anchor slug following GitHub's algorithm.

    To stay md051-compliant, `[text](#fragment)` links must reference the
    auto-generated slug by the renderer. We therefore use the GitHub
    algorithm (cf. https://github.com/jch/html-pipeline).

    Args:
        text: raw heading text (without backticks / internal punctuation).

    Returns:
        Normalised slug (lowercase, spaces -> dashes, punctuation removed).
    """
    s = text.lower()
    # Strip punctuation EXCEPT letters, digits, spaces, dashes, underscores.
    s = re.sub(r"[^\w\s-]", "", s, flags=re.UNICODE)
    # Spaces -> dashes
    s = re.sub(r"\s+", "-", s, flags=re.UNICODE)
    # Collapse consecutive dashes (`.` and other punctuation removed -> "")
    s = re.sub(r"-+", "-", s)
    return s.strip("-") or "section"


# ─── FRAGMENT LINK RESOLUTION ───────────────────────────────────────────────
_FRAGMENT_LINK_RE = re.compile(r"\[([^\]]*)\]\(#([^)]+)\)")


def _rewrite_fragment_links(
    md_text: str,
    anchor_map: dict[str, tuple[str, str]],
    current_relpath: str,
) -> str:
    """Rewrite `[text](#fragment)` links to point to the right file.

    Args:
        md_text         : MD generated by markdownify.
        anchor_map      : {anchor_id: (relative_filepath, github_slug)}.
        current_relpath: relative path of the current MD file (e.g. ``01-introduction.md``).

    Returns:
        MD with rewritten links:
        - `[text](#fragment)` if the anchor is in the same file (the renderer auto-generates the GitHub slug).
        - `[text](path.md#fragment)` if the anchor is in another file.
        No `{#id}` added to the MD - we rely on GitHub's standard slug (md051-compliant).
    """
    def replace_link(match: re.Match) -> str:
        text = match.group(1)
        anchor_id = match.group(2)
        if anchor_id not in anchor_map:
            # Anchor not found: leave the link as-is (visually broken, but kept for debug).
            return match.group(0)
        target_path, github_slug = anchor_map[anchor_id]
        if target_path == current_relpath:
            return f"[{text}](#{github_slug})"
        # Inter-chapter link: point to the right file.
        return f"[{text}]({target_path}#{github_slug})"

    return _FRAGMENT_LINK_RE.sub(replace_link, md_text)


# ─── TITLE EXTRACTION (corrected v2) ────────────────────────────────────────
def _extract_number_and_title(heading: Tag) -> tuple[str, str]:
    """Separate the title from the section number.

    The book's HTML has `<h2>Title<span class="chapter-number">1.1</span></h2>`
    or `<h1>Title</h1>` (number inside `<span class="chapter-heading-number">`).

    Returns:
        (title, number) with clean title and number as "1.1" / "1" / "".
    """
    num_span = heading.find("span", class_="chapter-number")
    if num_span:
        number = num_span.get_text(strip=True)
        num_span.extract()
        title = heading.get_text(" ", strip=True)
        num_span.insert(0, NavigableString(""))  # restore for next one
        return title, number

    # Fallback: title may end with "1.1" (weird concat)
    title = heading.get_text(" ", strip=True)
    m = re.match(r"^(.*?)(\d+(?:\.\d+){0,3})\s*$", title)
    if m:
        return m.group(1).strip().rstrip(":."), m.group(2)
    return title, ""


# ─── SPLIT INTO CHAPTERS ─────────────────────────────────────────────────────
def _split_chapters(soup: BeautifulSoup) -> list[dict]:
    """Split the body into usable chapters.

    The book's HTML structure is:
      <div class="chapter-heading">
        <span class="chapter-heading-number">Chapter N</span>   <- "Chapter N" label
        <a id="xxx"><h1>Title</h1></a>                          <- chapter title
      </div>
      <p>...</p>           <- chapter content (sections, code, etc.)
      <p>...</p>
      ...
      <div class="chapter-heading">                            <- next chapter
        ...

    The content of one chapter = siblings between two consecutive
    `div.chapter-heading` (or between a chapter-heading and the end of #main).

    Returns:
        [{"number": "1", "title": "Introduction", "anchor": "introduction",
          "body": Tag (wrapping chapter-heading + content)}, ...]
    """
    chapters = []
    main = soup.find(id="main")
    if not main:
        return chapters

    chap_divs = main.find_all("div", class_="chapter-heading")
    if not chap_divs:
        return chapters

    for i, div in enumerate(chap_divs):
        # Title: <a id><h1>Title</h1></a>
        a = div.find("a", id=True)
        if not a:
            continue
        h1 = a.find("h1")
        if not h1:
            continue
        anchor = a["id"]

        # Number: <span class="chapter-heading-number">Chapter N</span>
        # OR "Appendix A" in the title (fallback)
        number_span = div.find("span", class_="chapter-heading-number")
        if number_span:
            num_text = number_span.get_text(strip=True)
            m = re.match(r"Chapter\s+(\d+)", num_text, re.IGNORECASE)
            if m:
                number = m.group(1)
            else:
                m = re.match(r"Appendix\s+([A-Z])", num_text, re.IGNORECASE)
                number = m.group(1).upper() if m else ""
        else:
            number = ""

        title, _ = _extract_number_and_title(h1)

        # The span gives "Chapter 29" for appendices (continuous numbering).
        # Detect via the title: if "Appendix X:" at the start, override with X.
        m_appx = re.match(r"^Appendix\s+([A-Z])\s*[:\-–-]?\s*(.*)", title, re.IGNORECASE)
        if m_appx:
            number = m_appx.group(1).upper()
            title = m_appx.group(2).strip() or title
        elif not number:
            # Fallback if no span (shouldn't happen)
            pass

        # Wrapper: chapter-heading + all siblings until the next
        # chapter-heading (or end of #main).
        # IMPORTANT: capture next_sibling BEFORE the extract, otherwise
        # the soup mutates the next_sibling chain and we lose the following ones.
        next_chap = chap_divs[i + 1] if i + 1 < len(chap_divs) else None
        siblings_to_move = []
        sibling = div.next_sibling
        while sibling is not None and sibling is not next_chap:
            siblings_to_move.append(sibling)
            sibling = sibling.next_sibling

        wrapper = soup.new_tag("div")
        if div.parent is not None:
            wrapper.append(div.extract())
        else:
            wrapper.append(div)
        for s in siblings_to_move:
            if s.parent is not None:
                wrapper.append(s.extract())
            else:
                wrapper.append(s)

        chapters.append({
            "number": number,
            "title":  title,
            "anchor": anchor,
            "body":   wrapper,
        })

    return chapters


# ─── FILE GENERATION ────────────────────────────────────────────────────────
def _slugify_for_filename(text: str, fallback: str = "untitled") -> str:
    """Generate a kebab-case filename slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)        # strip punctuation
    text = re.sub(r"[\s_]+", "-", text)          # spaces/underscores -> dashes
    text = re.sub(r"-+", "-", text).strip("-")
    return text or fallback


def _chapter_filename(ch: dict, index: int) -> str:
    """Generate the filename: `NN-slug.md` (or `X-slug.md` for appendices).

    Special cases:
    - "About the author" -> `about-the-author.md` (no prefix, even if the source HTML gives it a chapter number).
    - Appendices A-D -> `X-slug.md` (subfolder `appendices/`).
    - Other unnumbered -> just the slug.
    """
    num = ch["number"]
    title_lower = ch["title"].strip().lower()

    # Special case: "About the author" / "About the Author"
    if title_lower in {"about the author", "about-the-author"}:
        return "about-the-author.md"

    slug = _slugify_for_filename(ch["title"], fallback=ch["anchor"])
    if num and num.isdigit():
        return f"{int(num):02d}-{slug}.md"
    if num and num.isalpha():
        return f"{num}-{slug}.md"
    return f"{slug}.md"


def _build_anchor_map(chapters: list[dict]) -> tuple[dict[str, tuple[str, str]], list[str]]:
    """Build the global anchor_id -> (file, github_slug) map.
    For each chapter, walk its headings (h1-h4) to find the anchors (`<a id="..."><hX>...</hX></a>`) and
    their heading text, then compute the GitHub slug. Store in ``anchor_map`` + return the list of relative
    paths per chapter (same index as ``chapters``).

    Returns:
        (anchor_map, chapter_relpaths)
        anchor_map       : {anchor_id: (relative_filepath, github_slug)}
        chapter_relpaths : [rel_path, ...] aligned with chapters
    """
    anchor_map: dict[str, tuple[str, str]] = {}
    chapter_relpaths: list[str] = []

    for i, ch in enumerate(chapters):
        is_appendix = ch["number"].isalpha()
        target_dir_name = "appendices" if is_appendix else ""
        filename = _chapter_filename(ch, i)
        rel_path = f"{target_dir_name}/{filename}" if target_dir_name else filename
        chapter_relpaths.append(rel_path)

        # Walk the headings in the body wrapper.
        # Search them BEFORE the anchors are unwrapped.
        for tag in ch["body"].find_all(["h1", "h2", "h3", "h4"]):
            a = tag.find_parent("a", id=True)
            if a:
                a_id = a["id"]
            elif tag.get("id"):
                # Case where a heading already carries an id directly.
                a_id = tag["id"]
            else:
                continue
            heading_text = _heading_text_without_chapter_number(tag)
            anchor_map[a_id] = (rel_path, _github_slugify(heading_text))

    return anchor_map, chapter_relpaths


def _heading_text_without_chapter_number(tag: Tag) -> str:
    """Clean text of a heading (without the span.chapter-number)."""
    clone = BeautifulSoup(str(tag), "html.parser")
    for span in clone.find_all("span", class_="chapter-number"):
        span.decompose()
    return clone.get_text(" ", strip=True)


def _render_chapter_md(
    ch: dict,
    total_chapters: int,
    book_meta: dict,
    anchor_map: dict[str, tuple[str, str]] | None,
    current_relpath: str,
) -> str:
    """Generate the MD of a chapter: frontmatter + heading + body.

    Args:
        ch              : chapter (with `body` soup wrapping the heading + content).
        total_chapters  : total chapter count (informational only).
        book_meta       : book metadata dict (title/author/version/source).
        anchor_map      : {anchor_id: (relative_filepath, github_slug)}. Used to rewrite fragment links.
        current_relpath : relative path of the current MD file.
    """
    from markdownify import markdownify as md

    # Clone the body to avoid mutating the original
    body_clone = BeautifulSoup(str(ch["body"]), "html.parser")

    # Unwrap <a id><hX>...</hX></a> to get clean headings
    _unwrap_heading_anchors_in(body_clone)

    # Strip <span class="chapter-number">NN.N</span> in headings
    # (the number is already represented in the frontmatter).
    for span in body_clone.find_all("span", class_="chapter-number"):
        span.decompose()

    # Strip <span class="chapter-heading-number"> (already represented in frontmatter)
    for span in body_clone.find_all("span", class_="chapter-heading-number"):
        span.decompose()

    # Strip residual attributes
    for el in body_clone.find_all(True):
        for attr in list(el.attrs):
            if attr.startswith("on") or attr == "style":  # type: ignore[attr-defined]
                del el.attrs[attr]

    # Strip <img> with base64 src (pollute the MD) - keep <img> HTTP(S)
    for img in body_clone.find_all("img"):
        src = img.get("src") or ""
        if isinstance(src, str) and src.startswith("data:"):
            alt = img.get("alt") or ""
            img.replace_with(NavigableString(f"![{alt}](image-omitted)"))

    # Mark <pre> as Odin
    for pre in body_clone.find_all("pre"):
        classes = pre.get("class") or []
        if isinstance(classes, str):
            classes = classes.split()
        if "language-odin" not in classes:
            classes.append("language-odin")
            pre["class"] = classes  # type: ignore[assignment]

    body_md = md(
        str(body_clone),
        heading_style="ATX",
        bullets="-",
        code_language_callback=lambda el: "odin",
    ).strip()

    # Rewrite `[text](#fragment)` links to correct file paths.
    # This is md051 resolution: we use the GitHub slug of the targeted heading.
    if anchor_map is not None:
        body_md = _rewrite_fragment_links(body_md, anchor_map, current_relpath)

    # Clean the level-1 heading that appears in the body (already in title)
    lines = body_md.split("\n")
    # The 1st heading may be "# 1 Introduction" -> strip it (duplicate with title)
    while lines and lines[0].startswith("# "):
        lines = lines[1:]
        if lines and lines[0].strip() == "":
            lines = lines[1:]
            break
    body_md = "\n".join(lines).strip()

    # Frontmatter conforming to FRONTMATTER_CONVENTIONS.md
    num = ch["number"]
    number_label = f"Chapter {num}" if num and num.isdigit() else (f"Appendix {num}" if num else "Section")
    return (
        "---\n"
        f"title: \"{number_label} - {ch['title']}\"\n"
        f"date: {book_meta['date']}\n"
        f"tags: [OdinRAG, kb, source/zylinski, reference, topic/odin, topic/book]\n"
        "type: reference\n"
        "status: active\n"
        "priority: 2\n"
        f"summary: \"Chapter {num} of '{book_meta['title']}' by {book_meta['author']}.\"\n"
        f"chapter_number: \"{num}\"\n"
        f"chapter_anchor: \"{ch['anchor']}\"\n"
        f"book_docId: {book_meta['docId']}\n"
        f"book_version: \"{book_meta['version']}\"\n"
        "---\n\n"
        f"# {ch['title']}\n\n"
        f"> **{number_label}** of *{book_meta['title']}* ({book_meta['author']}, v{book_meta['version']}).  \n"
        f"> Source: `{book_meta['source']}`\n\n"
        "---\n\n"
        f"{body_md}\n"
    )


def _render_book_readme(chapters: list[dict], book_meta: dict) -> str:
    """Generate the README.md = book index."""
    lines = [
        "---",
        f"title: \"{book_meta['title']}\"",
        f"date: {book_meta['date']}",
        "tags: [OdinRAG, kb, source/zylinski, reference, topic/odin, topic/book, doc/index]",
        "type: reference",
        "status: active",
        "priority: 1",
        f"summary: \"Index of '{book_meta['title']}' by {book_meta['author']} (v{book_meta['version']}). {len(chapters)} sections (chapters + appendices), ~656 code examples.\"",
        f"docId: {book_meta['docId']}",
        f"author: \"{book_meta['author']}\"",
        f"version: \"{book_meta['version']}\"",
        "---",
        "",
        f"# {book_meta['title']}",
        "",
        f"> **Author**: {book_meta['author']}  ",
        f"> **Source version**: {book_meta['version']}  ",
        f"> **Converted from**: `{book_meta['source']}`  ",
        f"> **Conversion date**: {book_meta['date']}",
        "",
        "**Reference book for the Odin language**. Each chapter is a standalone MD file for easy navigation and light Kilo context.",
        "",
        "## Table of Contents",
        "",
    ]

    # Group chapters by appendix vs main vs unnumbered
    main_chapters: list[dict] = []
    unnumbered: list[dict] = []
    for ch in chapters:
        title_lower = ch["title"].strip().lower()
        # "About the author": not a "Chapter N", even if num=33 in the HTML
        if title_lower in {"about the author", "about-the-author"}:
            unnumbered.append(ch)
        elif ch["number"].isdigit():
            main_chapters.append(ch)
        elif not ch["number"]:
            unnumbered.append(ch)
    appendices = [c for c in chapters if c["number"].isalpha()]

    for ch in main_chapters:
        filename = _chapter_filename(ch, 0)
        title = ch["title"]
        lines.append(f"- **Chapter {ch['number']}** - [{title}]({filename})")

    for ch in unnumbered:
        filename = _chapter_filename(ch, 0)
        lines.append(f"- **[{ch['title']}]({filename})**")

    if appendices:
        lines.append("")
        lines.append("### Appendices")
        lines.append("")
        for ch in appendices:
            filename = _chapter_filename(ch, 0)
            lines.append(f"- **Appendix {ch['number']}** - [{ch['title']}](appendices/{filename})")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## How to use this book")
    lines.append("")
    lines.append("1. **Navigation**: start with [Chapter 1](01-introduction.md), then follow the order.")
    lines.append("2. **Search by topic**: use Ctrl+F in each file, or grep on the `odin-book/` folder.")
    lines.append("3. **Kilo context**: to cite a chapter, open the corresponding `.md` file (~30-150 KB) - lighter than one single big file.")
    lines.append("4. **Code samples**: 656 examples in total, all preserved as ```odin` blocks.")
    lines.append("")
    lines.append("## Update")
    lines.append("")
    lines.append("When Karl publishes a new HTML version:")
    lines.append("1. Update the source file at the path you pass via `--src`")
    lines.append("2. Re-run the converter: `python _Helpers/lib/book_html_to_md.py`")
    lines.append("3. Verify the diff in `docs/karl_zylinski/odin-book/`")
    lines.append("")
    lines.append(f"## Metadata")
    lines.append("")
    lines.append(f"- **Title**: {book_meta['title']}")
    lines.append(f"- **Author**: {book_meta['author']}")
    lines.append(f"- **Version**: {book_meta['version']}")
    lines.append(f"- **Chapters**: {len(main_chapters) + len(unnumbered)} ({len(main_chapters)} numbered + {len(unnumbered)} unnumbered)")
    lines.append(f"- **Appendices**: {len(appendices)}")
    lines.append("")

    return "\n".join(lines)


# ─── MAIN PIPELINE ───────────────────────────────────────────────────────────
def _extract_metadata(soup: BeautifulSoup) -> dict:
    """Extract title/author/version from HTML BEFORE strip_chrome."""
    title_tag = soup.find("title")
    full_title = title_tag.get_text(strip=True) if title_tag else "Understanding the Odin Programming Language"
    clean_title = re.sub(r"\s+by\s+\w+\s+\w+$", "", full_title)

    author = "Karl Zylinski"
    version = "unknown"
    for p_tag in soup.find_all("p"):
        text = p_tag.get_text(" ", strip=True)
        m = re.match(r"Version\s+([\d.]+)\s*[-–]\s*(.+)", text)
        if m:
            version = m.group(1).strip()
            break

    return {
        "title":   clean_title,
        "author":  author,
        "version": version,
        "date":    "2026-06-28",
        "source":  "",  # filled after reading the file
        "docId":   "BOOK_ODIN_001",
    }


def _unwrap_heading_anchors_in(soup_or_tag: BeautifulSoup | Tag) -> None:
    """Transform `<a id="xxx"><hX>...</hX></a>` into `<hX id="xxx">...</hX>`.

    Required so that markdownify renders `# Title` (instead of `[# Title](#xxx)`).
    """
    for parent in soup_or_tag.find_all("a", id=True):
        heading = parent.find(["h1", "h2", "h3", "h4"])
        if heading is None:
            continue
        heading["id"] = parent["id"]
        parent.replace_with(heading)


def convert_book(html_path: str | Path, out_dir: str | Path) -> dict:
    """Convert the HTML into (1 README + N chapter files + appendices)."""
    src = Path(html_path)
    out = Path(out_dir)

    if not src.exists():
        raise FileNotFoundError(f"Source HTML not found: {src}")

    html = src.read_text(encoding="utf-8")
    soup = BeautifulSoup(html, "html.parser")

    # Metadata BEFORE strip_chrome (the cover contains "Version X.YY - Month, Year")
    book_meta = _extract_metadata(soup)
    book_meta["source"] = str(src)

    _strip_chrome(soup)
    _clean_attrs(soup)

    # Split into chapters
    chapters = _split_chapters(soup)
    if not chapters:
        raise RuntimeError("No chapter found - HTML structure changed?")

    # Create the folders
    out.mkdir(parents=True, exist_ok=True)
    (out / "appendices").mkdir(exist_ok=True)

    # Build the global anchor_id -> (relative_file, github_slug) map.
    # Used to rewrite `[text](#fragment)` to complete inter-chapter paths.
    # Must be computed BEFORE generating the files.
    anchor_map, chapter_relpaths = _build_anchor_map(chapters)

    # README
    readme = _render_book_readme(chapters, book_meta)
    (out / "README.md").write_text(readme, encoding="utf-8")

    # Chapters
    chapter_files = []
    for i, ch in enumerate(chapters):
        is_appendix = ch["number"].isalpha()
        target_dir = out / "appendices" if is_appendix else out
        filename = _chapter_filename(ch, i)
        target_path = target_dir / filename
        rel_path = chapter_relpaths[i]
        md_content = _render_chapter_md(
            ch, len(chapters), book_meta, anchor_map, rel_path,
        )
        target_path.write_text(md_content, encoding="utf-8")
        chapter_files.append({
            "filename": rel_path,
            "number":   ch["number"],
            "title":    ch["title"],
            "anchor":   ch["anchor"],
            "size":     len(md_content),
        })

    return {
        "metadata": book_meta,
        "chapter_count": len(chapters),
        "files": chapter_files,
        "readme": str(out / "README.md"),
    }


# ─── CLI ─────────────────────────────────────────────────────────────────────
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=_DESCRIPTION)
    parser.add_argument("--src", default=str(DEFAULT_SRC), help="Path of the source HTML")
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT), help="Output folder")
    parser.add_argument("--check", action="store_true", help="Dry-run: validate inputs, exit 0 if ready")
    args = parser.parse_args(argv)

    if args.check:
        src_path = Path(args.src)
        out_dir = Path(args.out_dir)
        if not src_path.is_file():
            print(f"[CHECK FAIL] Source not found: {src_path}", file=sys.stderr)
            return 1
        if not out_dir.exists():
            print(f"[CHECK FAIL] Output directory does not exist: {out_dir}", file=sys.stderr)
            return 1
        print(f"[CHECK OK] Source  : {src_path} ({src_path.stat().st_size:,} bytes)")
        print(f"[CHECK OK] Output  : {out_dir}")
        print(f"[CHECK OK] Ready to convert.")
        return 0

    print(f"Source  : {args.src}")
    print(f"Output  : {args.out_dir}")
    print()

    try:
        result = convert_book(args.src, args.out_dir)
    except FileNotFoundError as e:
        print(f"[ERR] {e}", file=sys.stderr)
        return 1

    print(f"Metadata : {result['metadata']['title']} (v{result['metadata']['version']})")
    print(f"Chapters : {result['chapter_count']}")
    print(f"README   : {result['readme']}")
    print()
    print("Generated files:")
    for f in result["files"]:
        print(f"  [{f['number']:>3}]  {f['size']:>8,} chars  {f['filename']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
