#!/usr/bin/env python3
"""
_Helpers/scrape-jakubtomsu.py - Blog Scraper (Jakub Tomsu)
[Re-entrant: skip if <slug>.md already exists; --force to rewrite]

Fetches ALL articles from the https://jakubtomsu.github.io blog and converts them into Markdown under docs/jakubtomsu/.

Usage:
    python _Helpers/scrape-jakubtomsu.py            # skip if already exported (re-entrant)
    python _Helpers/scrape-jakubtomsu.py --force    # force full rewrite
    python _Helpers/scrape-jakubtomsu.py --check    # dry-run (list what would be scraped)

Prerequisites:
    pip install requests markdownify beautifulsoup4 lxml

Discovery strategy:
    1. RSS feed        (/index.xml)         - Hugo, contains all canonical URLs
    2. Fallback slugs  - static list of known posts

Output:
    docs/jakubtomsu/<slug>.md (one file per article, with footer ">Source: <url>")
    docs/jakubtomsu/README.md (index with titles, dates, source URLs)

Behaviour:
    - Re-entrant: a .md already present (size > 0) is SKIPPED unless ``--force``.
    - --check: prints what would be scraped/skipped without writing anything.
    - Delay between requests: REQUEST_DELAY = 0.5s (politeness).

Exit codes:
    0   full success
    1   no article discovered (all strategies exhausted)
    2   partial success (at least one page failed)
"""
import argparse
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.http_client import discover_via_rss, slug_from_url  # noqa: E402
from lib.html2md import scrape_to_markdown  # noqa: E402

_DESCRIPTION = "Jakub Tomsu blog scraper (jakubtomsu.github.io) - re-entrant via RSS, --force to rewrite."

# ─── CONFIG ───────────────────────────────────────────────────────────────────
OUT = Path(__file__).resolve().parent.parent.parent / "docs" / "jakubtomsu"
OUT.mkdir(parents=True, exist_ok=True)

BASE_URL    = "https://jakubtomsu.github.io"
RSS_URL     = f"{BASE_URL}/index.xml"
POSTS_INDEX = f"{BASE_URL}/posts/"

REQUEST_DELAY = 0.5

FALLBACK_SLUGS: list[str] = [
    "bit_pools",
    "odin_comp_speed",
]

# ─── DISCOVERY ────────────────────────────────────────────────────────────────
def discover_all() -> tuple[list[str], str]:
    """Chain the discovery strategies. Returns (urls, source)."""
    print("[*] Discovering articles...")

    urls = discover_via_rss(
        RSS_URL, must_contain="/posts/",
        exclude_path=POSTS_INDEX,
    )
    if urls:
        print(f"  [+] {len(urls)} articles via RSS feed ({RSS_URL})")
        return urls, "rss"

    print("  [!] RSS unavailable, falling back to static list")
    urls = [f"{BASE_URL}/posts/{slug}" for slug in FALLBACK_SLUGS]
    print(f"  [+] {len(urls)} articles via fallback")
    return urls, "fallback"


# ─── README INDEX ─────────────────────────────────────────────────────────────
def _extract_title(filepath: Path) -> str:
    """Extract the first H1 heading from an .md file."""
    try:
        text = filepath.read_text(encoding="utf-8")
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("# ") or stripped.startswith("#\t"):
                return stripped.lstrip("#").strip()
    except Exception:
        pass
    return filepath.stem


def generate_readme(urls: list[str], out_dir: Path) -> None:
    """Write docs/jakubtomsu/README.md with titles, dates, source URLs."""
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Jakub Tomsu's blog",
        "",
        f"> Auto-generated by `scrape-jakubtomsu.py` on {now_iso}.",
        f"> {len(urls)} articles scraped from [{BASE_URL}]({BASE_URL}).",
        "",
        "| # | Title | File | Source URL |",
        "|---|-------|------|------------|",
    ]
    for i, url in enumerate(urls, 1):
        slug = slug_from_url(url, segment="posts")
        md_path = out_dir / f"{slug}.md"
        title = _extract_title(md_path) if md_path.exists() else slug.replace("-", " ").title()
        lines.append(f"| {i} | {title} | [{slug}.md](./{slug}.md) | [{url}]({url}) |")

    readme_path = out_dir / "README.md"
    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n[*] Index regenerated -> {readme_path}")


# ─── MAIN ─────────────────────────────────────────────────────────────────────
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=_DESCRIPTION)
    parser.add_argument(
        "--force", action="store_true",
        help="Rewrite every .md even if it already exists (default: skip).",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Dry-run: list what would be scraped/skipped without writing anything.",
    )
    args = parser.parse_args(argv)

    print("=" * 60)
    print("  Jakub Tomsu Blog Scraper - full coverage")
    print("=" * 60)

    urls, source = discover_all()
    if not urls:
        print("[ERR] No article discovered. Aborting.")
        return 1

    if args.check:
        print(f"\n[*] Dry-run: {len(urls)} articles (source: {source})")
        scraped_count = 0
        skipped_count = 0
        for i, url in enumerate(urls, 1):
            slug = slug_from_url(url, segment="posts")
            out_path = OUT / f"{slug}.md"
            if not args.force and out_path.exists() and out_path.stat().st_size > 0:
                print(f"  [{i:>2}/{len(urls)}] {slug}  [SKIP already present]")
                skipped_count += 1
            else:
                print(f"  [{i:>2}/{len(urls)}] {url}  [WOULD SCRAPE]")
                scraped_count += 1
        print(f"\n  {scraped_count} would be new, {skipped_count} already present")
        return 0

    action = "force rewrite" if args.force else "skip if present"
    print(f"\n[*] Scraping {len(urls)} articles (source: {source}, {action})...")
    scraped = failed = skipped = 0
    for i, url in enumerate(urls, 1):
        slug = slug_from_url(url, segment="posts")
        out_path = OUT / f"{slug}.md"
        if not args.force and out_path.exists() and out_path.stat().st_size > 0:
            print(f"  [{i:>2}/{len(urls)}] {slug}  [SKIP already present]")
            skipped += 1
            continue
        print(f"  [{i:>2}/{len(urls)}] {url}")
        if scrape_to_markdown(url, out_path):
            print(f"          [OK] {slug}.md")
            scraped += 1
        else:
            print(f"          [FAIL]")
            failed += 1
        time.sleep(REQUEST_DELAY)

    print("\n" + "=" * 60)
    print(f"  {scraped} new, {skipped} already present, {failed} failures")
    print(f"  Total: {len(urls)} targeted articles ({source})")
    print(f"  -> {OUT}")
    print("=" * 60)

    if scraped > 0 or args.force:
        generate_readme(urls, OUT)

    return 0 if failed == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
